DEFAULT_SERVER_PORT = 7777
DEFAULT_SERVER_LISTEN_ADDRESS = ''
DEFAULT_SERVER_ADDRESS = '127.0.0.1'

MAX_CONNECTIONS = 10
BUFFER_SIZE = 4096

ENCODING = 'utf-8'

ACTION = 'action'
TIME = 'time'
USER = 'user'
ACCOUNT_NAME = 'account_name'

PRESENCE = 'presence'
RESPONSE = 'response'
ERROR = 'error'
